apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: metrics
spec:
  accessModes: ["ReadWriteOnce"] # Azure overlays switch to ReadWriteMany on Azure Files
  resources:
    requests:
      storage: 1Gi
